/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CreditScoreRegistry } from "./CreditScoreRegistry";
export type { LoanManager } from "./LoanManager";
export type { SHGPool } from "./SHGPool";
export type { SHGPoolFactory } from "./SHGPoolFactory";
