/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LoanManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BACKEND_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "GROUP_LEADER_ROLE"
      | "addGroupLeader"
      | "approvalQuorum"
      | "approveLoan"
      | "borrowerLoans"
      | "checkDefault"
      | "createLoan"
      | "getBorrowerLoans"
      | "getLoan"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "loanApprovalCount"
      | "loanApprovals"
      | "loanCounter"
      | "loans"
      | "markDisbursed"
      | "markEmiPaid"
      | "pause"
      | "paused"
      | "removeGroupLeader"
      | "renounceRole"
      | "revokeRole"
      | "setApprovalQuorum"
      | "supportsInterface"
      | "totalLoans"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmiPaid"
      | "LoanApprovedByLeader"
      | "LoanCreated"
      | "LoanDefaulted"
      | "LoanDisbursed"
      | "LoanFullyApproved"
      | "LoanRepaid"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BACKEND_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GROUP_LEADER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addGroupLeader",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approvalQuorum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveLoan",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowerLoans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkDefault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLoan",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "loanApprovalCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loanApprovals",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "loanCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "markDisbursed",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markEmiPaid",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeGroupLeader",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalQuorum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLoans",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BACKEND_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GROUP_LEADER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addGroupLeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvalQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loanApprovalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loanApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loanCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDisbursed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markEmiPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeGroupLeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalLoans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace EmiPaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    emiNumber: BigNumberish,
    emiAmountPaise: BigNumberish,
    upiRef: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    emiNumber: bigint,
    emiAmountPaise: bigint,
    upiRef: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    emiNumber: bigint;
    emiAmountPaise: bigint;
    upiRef: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanApprovedByLeaderEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    approver: AddressLike,
    approvalCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    approver: string,
    approvalCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    approver: string;
    approvalCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanCreatedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    principalPaise: BigNumberish,
    interestRateBps: BigNumberish,
    tenureMonths: BigNumberish,
    emiAmountPaise: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    principalPaise: bigint,
    interestRateBps: bigint,
    tenureMonths: bigint,
    emiAmountPaise: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    principalPaise: bigint;
    interestRateBps: bigint;
    tenureMonths: bigint;
    emiAmountPaise: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    overdueBy: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    overdueBy: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    overdueBy: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDisbursedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    principalPaise: BigNumberish,
    txRef: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    principalPaise: bigint,
    txRef: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    principalPaise: bigint;
    txRef: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanFullyApprovedEvent {
  export type InputTuple = [loanId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [loanId: bigint, timestamp: bigint];
  export interface OutputObject {
    loanId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LoanManager extends BaseContract {
  connect(runner?: ContractRunner | null): LoanManager;
  waitForDeployment(): Promise<this>;

  interface: LoanManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BACKEND_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GROUP_LEADER_ROLE: TypedContractMethod<[], [string], "view">;

  addGroupLeader: TypedContractMethod<
    [leader: AddressLike],
    [void],
    "nonpayable"
  >;

  approvalQuorum: TypedContractMethod<[], [bigint], "view">;

  approveLoan: TypedContractMethod<
    [loanId: BigNumberish, leader: AddressLike],
    [void],
    "nonpayable"
  >;

  borrowerLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  checkDefault: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createLoan: TypedContractMethod<
    [
      borrower: AddressLike,
      principalPaise: BigNumberish,
      interestRateBps: BigNumberish,
      tenureMonths: BigNumberish,
      shgPoolId: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getBorrowerLoans: TypedContractMethod<
    [borrower: AddressLike],
    [bigint[]],
    "view"
  >;

  getLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        borrower: string;
        shgPoolId: string;
        principalPaise: bigint;
        interestRateBps: bigint;
        emiAmountPaise: bigint;
        tenureMonths: bigint;
        disbursedAt: bigint;
        nextEmiDueAt: bigint;
        emisPaid: bigint;
        status: bigint;
        disbursalTxRef: string;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  loanApprovalCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  loanApprovals: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  loanCounter: TypedContractMethod<[], [bigint], "view">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        borrower: string;
        shgPoolId: string;
        principalPaise: bigint;
        interestRateBps: bigint;
        emiAmountPaise: bigint;
        tenureMonths: bigint;
        disbursedAt: bigint;
        nextEmiDueAt: bigint;
        emisPaid: bigint;
        status: bigint;
        disbursalTxRef: string;
      }
    ],
    "view"
  >;

  markDisbursed: TypedContractMethod<
    [loanId: BigNumberish, txRef: BytesLike],
    [void],
    "nonpayable"
  >;

  markEmiPaid: TypedContractMethod<
    [loanId: BigNumberish, upiRef: BytesLike],
    [void],
    "nonpayable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  removeGroupLeader: TypedContractMethod<
    [leader: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setApprovalQuorum: TypedContractMethod<
    [newQuorum: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalLoans: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BACKEND_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GROUP_LEADER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addGroupLeader"
  ): TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approvalQuorum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish, leader: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "borrowerLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkDefault"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createLoan"
  ): TypedContractMethod<
    [
      borrower: AddressLike,
      principalPaise: BigNumberish,
      interestRateBps: BigNumberish,
      tenureMonths: BigNumberish,
      shgPoolId: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBorrowerLoans"
  ): TypedContractMethod<[borrower: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        borrower: string;
        shgPoolId: string;
        principalPaise: bigint;
        interestRateBps: bigint;
        emiAmountPaise: bigint;
        tenureMonths: bigint;
        disbursedAt: bigint;
        nextEmiDueAt: bigint;
        emisPaid: bigint;
        status: bigint;
        disbursalTxRef: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "loanApprovalCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "loanApprovals"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "loanCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        borrower: string;
        shgPoolId: string;
        principalPaise: bigint;
        interestRateBps: bigint;
        emiAmountPaise: bigint;
        tenureMonths: bigint;
        disbursedAt: bigint;
        nextEmiDueAt: bigint;
        emisPaid: bigint;
        status: bigint;
        disbursalTxRef: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDisbursed"
  ): TypedContractMethod<
    [loanId: BigNumberish, txRef: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markEmiPaid"
  ): TypedContractMethod<
    [loanId: BigNumberish, upiRef: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeGroupLeader"
  ): TypedContractMethod<[leader: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalQuorum"
  ): TypedContractMethod<[newQuorum: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalLoans"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "EmiPaid"
  ): TypedContractEvent<
    EmiPaidEvent.InputTuple,
    EmiPaidEvent.OutputTuple,
    EmiPaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanApprovedByLeader"
  ): TypedContractEvent<
    LoanApprovedByLeaderEvent.InputTuple,
    LoanApprovedByLeaderEvent.OutputTuple,
    LoanApprovedByLeaderEvent.OutputObject
  >;
  getEvent(
    key: "LoanCreated"
  ): TypedContractEvent<
    LoanCreatedEvent.InputTuple,
    LoanCreatedEvent.OutputTuple,
    LoanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDisbursed"
  ): TypedContractEvent<
    LoanDisbursedEvent.InputTuple,
    LoanDisbursedEvent.OutputTuple,
    LoanDisbursedEvent.OutputObject
  >;
  getEvent(
    key: "LoanFullyApproved"
  ): TypedContractEvent<
    LoanFullyApprovedEvent.InputTuple,
    LoanFullyApprovedEvent.OutputTuple,
    LoanFullyApprovedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "EmiPaid(uint256,uint256,uint256,bytes32,uint256)": TypedContractEvent<
      EmiPaidEvent.InputTuple,
      EmiPaidEvent.OutputTuple,
      EmiPaidEvent.OutputObject
    >;
    EmiPaid: TypedContractEvent<
      EmiPaidEvent.InputTuple,
      EmiPaidEvent.OutputTuple,
      EmiPaidEvent.OutputObject
    >;

    "LoanApprovedByLeader(uint256,address,uint256,uint256)": TypedContractEvent<
      LoanApprovedByLeaderEvent.InputTuple,
      LoanApprovedByLeaderEvent.OutputTuple,
      LoanApprovedByLeaderEvent.OutputObject
    >;
    LoanApprovedByLeader: TypedContractEvent<
      LoanApprovedByLeaderEvent.InputTuple,
      LoanApprovedByLeaderEvent.OutputTuple,
      LoanApprovedByLeaderEvent.OutputObject
    >;

    "LoanCreated(uint256,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;
    LoanCreated: TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;

    "LoanDefaulted(uint256,address,uint256,uint256)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanDisbursed(uint256,address,uint256,bytes32,uint256)": TypedContractEvent<
      LoanDisbursedEvent.InputTuple,
      LoanDisbursedEvent.OutputTuple,
      LoanDisbursedEvent.OutputObject
    >;
    LoanDisbursed: TypedContractEvent<
      LoanDisbursedEvent.InputTuple,
      LoanDisbursedEvent.OutputTuple,
      LoanDisbursedEvent.OutputObject
    >;

    "LoanFullyApproved(uint256,uint256)": TypedContractEvent<
      LoanFullyApprovedEvent.InputTuple,
      LoanFullyApprovedEvent.OutputTuple,
      LoanFullyApprovedEvent.OutputObject
    >;
    LoanFullyApproved: TypedContractEvent<
      LoanFullyApprovedEvent.InputTuple,
      LoanFullyApprovedEvent.OutputTuple,
      LoanFullyApprovedEvent.OutputObject
    >;

    "LoanRepaid(uint256,address,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
